import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { ChartColumnBigIcon } from 'lucide-react';
import Link from 'next/link';

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${poppins.variable} antialiased`}>
        <nav className='bg-primary p-4 text-white h-20 flex items-center justify-between'>
          <Link href='/' className='font-bold text-2xl flex items-center gap-1'>
            <ChartColumnBigIcon className='text-lime-500' />
            <span>NextCash</span>
          </Link>
          <div>auth button</div>
        </nav>
        {children}
      </body>
    </html>
  );
};
